scenario_cfg: # TODO
  dataset_name: MMBench
    dataset_cfg:
      base_data_path: data/datasets/LAMM/2D_Benchmark
      ppl: True
      option_content: False
      option: '' # defined in code

eval_cfg:
  instruction_cfg: 
    query_type: query_pool
    prompt_assigned_ids: 4
    template_assigned_ids: 1
  inferencer_cfg:
    inferencer_type: PPL
    batch_size: 32
    CoT: True
    max_new_tokens: 256
    CoT_split: True
  metric_cfg:
    metric_type: Calibration